version: "3.7"
services:
  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      RAILS_ENV: development
volumes:
  gem_cache:
  db_data:
  node_modules:
